# production-deploy.yml
name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build client
        run: dotnet build Web/KatiesGarden.Web/Client/KatiesGarden.Web.Client.csproj --configuration Release

      - name: Build API
        run: dotnet build Api/KatiesGarden.Api.csproj --configuration Release

      - name: Publish client
        run: dotnet publish Web/KatiesGarden.Web/Client/KatiesGarden.Web.Client.csproj --configuration Release --output publish_output

      - name: Deploy to Production
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "publish_output/wwwroot"
          api_location: "Api"
          output_location: ""
