name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  # Deploy to production when merged to main
  build_and_deploy_production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy to Production
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_CLIFF_084ED4903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Web/KatiesGarden.Web/Client"
          api_location: "Api"
          output_location: "wwwroot"
